[py3] Issue with slots and multiple inheritance
Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 185, in main
    _main(opts)
  File "..\Mopy\bash\bash.py", line 282, in _main
    from . import basher, balt
  File "..\Mopy\bash\basher\__init__.py", line 3427, in <module>
    class BashNotebook(wx.Notebook, balt.TabDragMixin):
TypeError: multiple bases have instance lay-out conflict

TODO: See if there's a better fix other than just dropping slots?