Squashed version of inf-190-wizard-api
commit 76b0f26a4246c289edeefd9ad094b4f421fa13cc
Author: Infernio <infernio@icloud.com>
Date:   Thu Jan 28 18:18:18 2021 +0100

    Drop old APIs

    Both the old WizardDialog and WithFirstShow are now obsolete, so drop
    them.

commit dd3013aa8dcb7bbf4b3cd5a358d9c27e17342ae4
Author: Infernio <infernio@icloud.com>
Date:   Thu Jan 28 18:44:24 2021 +0100

    Rework BAIN wizards to use the wizard API

    Small addition to the wizards API needed, I forgot about that one.

    belt is now wx-free. This may also fix that one odd bug where sometimes
    the finish button doesn't behave properly. And even if it doesn't, at
    least now we can investigate why.

commit 00083bd4350fd36d333bed8ec58a65cfd5dd5a96
Author: Infernio <infernio@icloud.com>
Date:   Thu Jan 28 18:04:12 2021 +0100

    Rework FOMODs to use the wizard API

    1. No more wx usages, explicit or implicit, in gui_fomod
    2. Several hacks have gone the way of the dodo
    3. Less code (~40 lines gone)

    What's not to like :)

commit 0b766f6431e5025c48cac990eb891357f9b439bd
Author: Infernio <infernio@icloud.com>
Date:   Thu Jan 28 12:45:24 2021 +0100

    Create a custom wizard API

    Completely de-wx'd. Only problem is that it has a tiny bit of flicker
    when changing pages. I can't tell what the wxWidgets wizard
    implementation does differently that lets it avoid that. In the end, I
    decided not to let perfect be the enemy of good. It's a tiny bit of
    flicker, which is a small price to pay for fixing the horrible back
    button issue and getting entirely de-wx'd wizards.

commit 5c8deaba3e6c5c9032199f1e9455d065046f6855
Author: Infernio <infernio@icloud.com>
Date:   Thu Jan 28 15:51:09 2021 +0100

    fomod: ASCII-decode everything if we have bytes

    Same irritating nonsense that pyyaml pulls in py2 as well. Everything
    that can't be ASCII-decoded is returned as unicode, everything else as
    str. This blows up on io.StringIO:

    Traceback (most recent call last):
      File "bash\balt.pyo", line 1832, in Execute
      File "bash\basher\installer_links.pyo", line 584, in Execute
      File "bash\basher\installer_links.pyo", line 569, in _try_installer
      File "bash\balt.pyo", line 880, in _conversation_wrapper
      File "bash\basher\installer_links.pyo", line 218, in Execute
      File "bash\basher__init.pyo", line 3287, in RefreshUIMods
      File "bash\balt.pyo", line 1117, in RefreshUI
      File "bash\balt.pyo", line 1130, in _refresh_details
      File "bash\basher__init.pyo", line 157, in SetDetails
      File "bash\basher__init.pyo", line 155, in _setDetails
      File "bash\basher__init.pyo", line 2863, in SetFile
      File "bash\basher__init.pyo", line 2963, in RefreshInfoPage
      File "bash\basher__init.pyo", line 2910, in dumpFiles
    TypeError: unicode argument expected, got 'str'

commit 1190b656d1a0fb125569b591bfd022da9bdff1f1
Author: Kenneth M. Glassey <awereal@gmail.com>
Date:   Wed Jan 27 14:24:48 2021 -0500

    fomod: Fix order attribute getting ignored

    Retrieve the order attribute from the <plugins> element.

    Retrieve order attribute from optionalFileGroups instead of installStep.

commit 6b109548353f7b33764082f230f1ab9acfb18f9e
Author: Infernio <infernio@icloud.com>
Date:   Wed Jan 27 19:27:12 2021 +0100

    fomod: Skip first page if it's not visible

    Really just involves deduplicating the logic from move_to_next.
    Also added some comments, this file really does need some more :)

    Co-authored-by: "Kenneth M. Glassey" <awereal@gmail.com>