[py3] traceback no longer takes the exception as an argument
Traceback (most recent call last):
  File "..\Mopy\Wrye Bash Launcher.py", line 32, in <module>
    bash.main(opts)
  File "..\Mopy\bash\bash.py", line 194, in main
    traceback.format_exc(e)
  File "C:\Code\Python\3.8\lib\traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "C:\Code\Python\3.8\lib\traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "C:\Code\Python\3.8\lib\traceback.py", line 509, in __init__
    self.stack = StackSummary.extract(
  File "C:\Code\Python\3.8\lib\traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'KeyError' and 'int'