New crashes - rip off defaullts I MelBase
Traceback (most recent call last):
  File "bash\bash.py", line 340, in _main
    bashIni, bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
  File "bash\bash.py", line 460, in _detect_game
    bush_game = _import_bush_and_set_game(opts, bashIni)
  File "bash\bash.py", line 477, in _import_bush_and_set_game
    from . import bush
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 62, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\bush.py", line 33, in <module>
    from . import game as game_init
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 75, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\game\__init__.py", line 33, in <module>
    from .. import brec
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 75, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\brec\__init__.py", line 32, in <module>
    from .common_records import *
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 62, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\brec\common_records.py", line 212, in <module>
    class MreGmstBase(MelRecord):
  File "bash\brec\common_records.py", line 226, in MreGmstBase
    fallback=MelSInt32(b'DATA', u'value')
  File "bash\brec\record_structs.py", line 53, in __init__
    element.getDefaulters(self, u'')
  File "bash\brec\advanced_elements.py", line 860, in getDefaulters
    element.getDefaulters(mel_set_instance, mel_key)
  File "bash\brec\basic_elements.py", line 204, in getDefaulters
    raise SyntaxError(u'%s duplicate attr %s' % (self, self.attr))
ImportError: caused by ImportError(u'caused by ImportError(u\'caused by ImportError(u"caused by SyntaxError(u\\\'[]: value duplicate attr value\\\',)",)\',)',)

Introduced in 082c30563d76e3c8d9831b902dc154a268bf3575 where MelUInt32
has now default 0.Enough with defaults