[!]SSS TTT inline __getCase: RRR
Change: before Path would compare with anything Falsy alright (say with
empty lists). That didn't sound quite right so I changed it but TTT -
especially comparison with None could be used somewhere (but decided
to drop that too) --> see edit I kept it
We now avoid the __getCase call which given the importance of Path
performance seems worth it - although probably most comparisons are
between Paths. Note we always call decoder now (was avoided in falsy case
but those should be few) so, apart from Falsy and unicode, we are one
frame less now.

EEE: u'' normpath -> u'.' duh - so kept the None comp:

@@ -933,3 +933,5 @@ def __eq__(self, other):
             return self._cs == other._cs
-        return self._cs == os.path.normcase(os.path.normpath(decoder(other)))
+        dec = decoder(other) # get unicode or None - will blow on most else
+        return self._cs == (os.path.normcase(os.path.normpath(dec)) if dec
+            else dec)
     def __ne__(self, other):
@@ -937,3 +939,5 @@ def __ne__(self, other):
             return self._cs != other._cs
-        return self._cs != os.path.normcase(os.path.normpath(decoder(other)))
+        dec = decoder(other)
+        return self._cs != (os.path.normcase(os.path.normpath(dec)) if dec
+            else dec)
     def __lt__(self, other):
@@ -941,3 +945,5 @@ def __lt__(self, other):
...

Closer to previous on this (previously Happy) path - will only decode b''
which it didn't before

    Profile _main before inline __getCase
    18148523 function calls (18121204 primitive calls) in 12.068 seconds
	inline
    18111904 function calls (18084585 primitive calls) in 12.590 seconds

squash!     [!]SSS TTT inline __getCase:

@@ -930,3 +930,4 @@ def __eq__(self, other):
             return self._cs == other._cs
-        dec = decoder(other) # get unicode or None - will blow on most else
+        # get unicode or None - will blow on most other types - identical below
+        dec = other if isinstance(other, unicode) else decoder(other)
         return self._cs == (os.path.normcase(os.path.normpath(dec)) if dec

	isinstance
    18051171 function calls (18023852 primitive calls) in 12.745 seconds

See:

https://github.com/wrye-bash/wrye-bash/commit/d8e94fdb91ced1a91ef3a99a90978fe704db23aa

Before     [!]SSS TTT inline __getCase:
bash.py  435 _main: 2730355 function calls (2724884 primitive calls) in 2.970 seconds

After     [!]SSS TTT inline __getCase:
bash.py  435 _main: 2730355 function calls (2724884 primitive calls) in 2.992 seconds

So no diff in function calls - this means that we were never checking str
vs self - if this commit makes also no diff then we are only (mostly)
checking Path vs self (unlikely). Otherwise will be faster (decoder did
the isinstance check - will be still done but for None only)

Infernio:

FFF Don't compare bool to Path

Interesting, this just showed up on Discord:

Traceback (most recent call last):
  File "bash\gui\events.pyo", line 165, in _post
  File "bash\balt.pyo", line 875, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 175, in PatchExecute
  File "bash\patcher\patch_files.pyo", line 296, in buildPatch
  File "bash\brec\record_groups.pyo", line 322, in keepRecords
  File "bash\bolt.pyo", line 934, in eq
  File "bash\bolt.pyo", line 140, in decoder
  File "bash\bolt.pyo", line 121, in getbestencoding
  File "chardet__init__.pyo", line 37, in detect
TypeError: Expected object of type bytes or bytearray, got: <type 'bool'>
This is from back when the line was

dec = decoder(other) # get unicode or None - will blow on most else
So it looks like we do compare paths to other things in keepRecords.