[py3] Reading from file already decoded.
Note: Need to test malformed files to check it doesn't crash

Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 185, in main
    _main(opts)
  File "..\Mopy\bash\bash.py", line 361, in _main
    app.Init() # Link.Frame is set here !
  File "..\Mopy\bash\basher\__init__.py", line 4041, in Init
    self.InitData(progress)
  File "..\Mopy\bash\basher\__init__.py", line 4078, in InitData
    bosh.modInfos.refresh(booting=True)
  File "..\Mopy\bash\bosh\__init__.py", line 1915, in refresh
    lo_changed = self.refreshLoadOrder(
  File "..\Mopy\bash\bosh\__init__.py", line 1663, in _modinfos_cache_wrapper
    lord_func(self, *args, **kwargs)
  File "..\Mopy\bash\bosh\__init__.py", line 1770, in refreshLoadOrder
    load_order.refresh_lo(cached=not forceRefresh,
  File "..\Mopy\bash\load_order.py", line 305, in refresh_lo
    _update_cache(lo, active)
  File "..\Mopy\bash\load_order.py", line 254, in _update_cache
    lord, acti_sorted = _game_handle.get_load_order(lord, acti_sorted,
  File "..\Mopy\bash\games.py", line 227, in get_load_order
    lo, active = self._cached_or_fetch(cached_load_order,
  File "..\Mopy\bash\games.py", line 768, in _cached_or_fetch
    return self._fetch_load_order(cached_load_order, cached_active)
  File "..\Mopy\bash\games.py", line 778, in _fetch_load_order
    active, lo = self._parse_modfile(self.plugins_txt_path) # empty if not exists
  File "..\Mopy\bash\games.py", line 354, in _parse_modfile
    acti, _lo = _parse_plugins_txt_(path, self.mod_infos, _star=self._star)
  File "C:\Users\Lojack\Desktop\wrye-bash-dev\Mopy\bash\games.py", line 101, in _parse_plugins_txt_
    test2 = str(modname, encoding)
TypeError: decoding str is not supported