Fix MelArray.mapFids with mixed FormID status
E.g. MrePgrd - PGRL has a FormID in the prelude but no FormID in the
element. Would blow up like this:

Traceback (most recent call last):
  File "bash\basher\patcher_dialog.pyo", line 174, in PatchExecute
  File "bash\patcher\patch_files.pyo", line 214, in scanLoadMods
  File "bash\mod_files.pyo", line 268, in load
  File "bash\mod_files.pyo", line 345, in _convert_fids
  File "bash\brec\record_groups.pyo", line 1744, in convertFids
  File "bash\brec\record_groups.pyo", line 1530, in convertFids
  File "bash\brec\record_groups.pyo", line 1253, in convertFids
  File "bash\brec\record_groups.pyo", line 945, in convertFids
  File "bash\brec\record_structs.pyo", line 515, in convertFids
  File "bash\brec\record_structs.pyo", line 160, in convertFids
  File "bash\brec\basic_elements.pyo", line 531, in mapFids
  File "bash\brec\advanced_elements.pyo", line 374, in mapFids
  File "bash\brec\basic_elements.pyo", line 201, in mapFids
AbstractError: <m_point: 0> does not have FormIDs