Fix for Recalculate Record Counts:
I run across this trying to finalize the getNumRecords commit (next) -
this lead to LoadFactory and the rest of this branch. Turns out that the
MobBase.getNumRecords was only (?) called in this menu that was broken
(since f8678228fe82c999e4b5d2645b1494109dbac459 ?)

Traceback (most recent call last):
  File "bash\balt.py", line 1832, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 116, in Execute
    modFile.load(True)
  File "bash\mod_files.py", line 268, in load
    self._convert_fids(to_long=True)
  File "bash\mod_files.py", line 345, in _convert_fids
    target_top.convertFids(mapper, to_long)
  File "bash\brec\record_groups.py", line 153, in convertFids
    raise AbstractError(u'convertFids not implemented')
bash.exception.AbstractError: convertFids not implemented

Was caused by target_top being MobBase - so one first attempt (that I
did not like but wanted to test) was to pass all record (was it all?)
"types" to be loaded by their respective class:

@@ -113,5 +113,5 @@ class Mod_RecalcRecordCounts(OneItemLink):
         def Execute(self):
-        loadFactory = mod_files.LoadFactory(True)
+        loadFactory = mod_files.LoadFactory(True, *MreRecord.type_class.values())

This would convert fids and hopefully work - although slow (why convert
fids when we only want the records counts?). Turns out this blew with:

Traceback (most recent call last):
  File "bash\balt.py", line 1832, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 120, in Execute
    topType, block.getNumRecords()))
  File "bash\brec\record_groups.py", line 1181, in getNumRecords
    count += 1 + len(self.getUsedBlocks()) + len(
  File "bash\brec\record_groups.py", line 1128, in getUsedBlocks
    return {x.getBsb()[0] for x in self.cellBlocks}
  File "bash\brec\record_groups.py", line 1128, in <setcomp>
    return {x.getBsb()[0] for x in self.cellBlocks}
  File "bash\brec\record_groups.py", line 892, in getBsb
    baseFid = cell.fid & 0x00FFFFFF
TypeError: unsupported operand type(s) for &: 'tuple' and 'int'

deep inside record_groups.MobCells.getNumRecords - so this too was not
called and expected short ids - since
f8678228fe82c999e4b5d2645b1494109dbac459 ? We relax the latter's API
by making convert fids optional (which as noted seems a valid
requirement). This seems to work - bugdump (wrye log here?):

Cobl main:
mod_links.py  120 Execute: ACTI GRUP has 111 records
mod_links.py  120 Execute: ALCH GRUP has 39 records
mod_links.py  120 Execute: AMMO GRUP has 17 records
mod_links.py  120 Execute: APPA GRUP has 2 records
mod_links.py  120 Execute: BOOK GRUP has 222 records
mod_links.py  120 Execute: CELL GRUP has 178 records
mod_links.py  120 Execute: CLOT GRUP has 8 records
mod_links.py  120 Execute: CONT GRUP has 113 records
mod_links.py  120 Execute: CREA GRUP has 2 records
mod_links.py  120 Execute: EFSH GRUP has 16 records
mod_links.py  120 Execute: ENCH GRUP has 70 records
mod_links.py  120 Execute: EYES GRUP has 153 records
mod_links.py  120 Execute: FACT GRUP has 25 records
mod_links.py  120 Execute: FLOR GRUP has 3 records
mod_links.py  120 Execute: GLOB GRUP has 61 records
mod_links.py  120 Execute: GMST GRUP has 2 records
mod_links.py  120 Execute: HAIR GRUP has 162 records
mod_links.py  120 Execute: INGR GRUP has 181 records
mod_links.py  120 Execute: LIGH GRUP has 2 records
mod_links.py  120 Execute: LVLI GRUP has 1073 records
mod_links.py  120 Execute: MISC GRUP has 478 records
mod_links.py  120 Execute: NPC_ GRUP has 2 records
mod_links.py  120 Execute: QUST GRUP has 64 records
mod_links.py  120 Execute: RACE GRUP has 8 records
mod_links.py  120 Execute: SCPT GRUP has 465 records
mod_links.py  120 Execute: SOUN GRUP has 3 records
mod_links.py  120 Execute: SPEL GRUP has 136 records
mod_links.py  120 Execute: STAT GRUP has 24 records
mod_links.py  120 Execute: WEAP GRUP has 110 records

Now are the counts right? to be continued

Mopy/bash/bosh/__init__.py:
comments from 27e65c64535a9b16d62208771c3863b6c55fe720 not needed since
42746d52e7740a2ed5e85bb48637ca14ba4dad4f

+ Mopy/bash/brec/record_groups.py: MobCells.getNumRecords comments

inlined used once, see second traceback plus calculate once (duh) -
what is a Bsb? :P

Infernio:
Not a clue to be honest 😅
Block subblock?

Under #312 #480